# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Social Economy Data Lab
author: Social Economy Data Lab
email: contact@socialeconomydatalab.org
description: >- # this means to ignore newlines until "baseurl:"
  The Social Economy Data Lab is home to a set of projects which are developing
  ways in which charities, social enterprises, grant funders and social investors
  in the UK can collectively make better use of data
keywords: social, investment, economy, open, data, labs, spec, standard, civic, trust, specification, power to change
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
permalink: pretty

domain: socialeconomydatalab.org
twitter_username: SocEconDataLab
github_username: SocialEconomyDataLab
contact_email: contact@socialeconomydatalab.org

timezone: Europe/London

# Build settings
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
